// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ItemOps struct {
	Create *Item   `json:"create"`
	Update *string `json:"update"`
	Delete *string `json:"delete"`
}

type NewItem struct {
	Name   string `json:"name"`
	UserID int    `json:"user_id"`
}

type NewUser struct {
	Name string `json:"name"`
}

type UpdateItem struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	UserID int    `json:"user_id"`
}

type UpdateUser struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UserOps struct {
	Create *User   `json:"create"`
	Update *string `json:"update"`
	Delete *string `json:"delete"`
}
