apiVersion: v1
kind: Service
metadata:
  name: go-crud
spec:
  type: NodePort
  selector:
    app: go-crud
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud
spec:
  selector:
    matchLabels:
      app: go-crud
  template:
    metadata:
      labels:
        app: go-crud
    spec:
      containers:
      - name: go-crud
        image: davidyap/go-mysql-crud:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: ""
          - name: DB_HOST
            value: mysql-go
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: tester
